version: '2'
services:
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    volumes:
      - 'pgadminconfig_data:/var/lib/pgadmin'
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DEFAULT_EMAIL: viku@kvimalan.com
volumes:
  pgadminconfig_data: null
